name: test-workflow

on:
  push:
    paths:
      - '.github/**'
      - 'code/**'
      - 'OBMD_DPD/**'
  pull_request:
    paths:
      - '.github/**'
      - 'code/**'
      - 'OBMD_DPD/**'

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello from GitHub Actions!"
